version: '3.8'

services:
  competitor:
    container_name: competitor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATA_DIR=/app/data
      - LOG_DIR=/app/logs
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=False
      - LOG_LEVEL=INFO
    volumes:
      - /srv/competitor/data:/app/data
      - /srv/competitor/logs:/app/logs
    restart: unless-stopped
    env_file:
      - .env
